### ISSUE TITLE
Adding image into a clipboard

### ISSUE THREAD

**Issue by photopea** [w3c/clipboard-apis#80] opened 2018-06-16 19:33 UTC
I am a developer of www.Photopea.com . It is an in-browser image editor used by thousands of people every day. Copy-pasting images between Photopea and other programs (usually within a browser) is a crucial thing for us. 

We listen to "paste" event on "window", then we loop through Event.clipboardData.items and call getAsString() / getAsFile() on each item.

We need to copy-paste things within Photopea, but writing images to a "system" clipboard is not possible at the moment, so we have to implement our local clipboard for Photopea (which contains data copied within Photopea).

When the user presses Ctrl+V, we detect both "paste" event, and the keyboard shortcut combination. But it is not clear, whether we should paste the content of a local clipboard, or the system clipboard. The solution would be to paste the "most recent" content (i.e. depending on the time of creation of the clipboard content), but the current API does not give us the creation time of the system clipboard content.

There would not be any such problem, if we could simply write images to the system clipboard, instead of creating a local one. Can you make sure it is possible in the current API, or at least expose the creation time of clipboard data?

When a user creates a new image in a native image editor, the Width and Height fields are pre-set according to the dimension of a system clipboard image (if there is any). This can not be done in the web. Could you also make sure, that apps can access the clipboard content without a user pressing Ctrl+V?

There are about 10 people every week writing me to implement / fix these things, so I am really desperate and don't know what to do :(

**Comment by garykac** [comment] 2018-08-30 17:46
Duplicate of #44

**Closed by garykac** 2018-08-30 17:46 UTC
